version: '3.8'

services:
  lftpsync:
    image: nitrobass24/lftpsync:ubuntu
    container_name: lftpsync
    volumes:
      - /mnt/pool/stephen/cron.log:/var/log/cron.log
      - /mnt/pool/lftpsync:/app/data
      - /mnt/pool/data/downloads/import:/app/finaldata
      - /mnt/pool/stephen/sftpsync.sh:/app/my-script.sh
    working_dir: /app
    entrypoint: ["bash", "/app/my-script.sh"]
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Chicago
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
